"""Nothing enters the corpus unproven, and the proof is two runs of the shipped verifier.

A task is *live* when it discriminates: with no patch it must **FAIL**, and with its own
reference patch it must **PASS** — with the executed node-id set equal to the declared one and
nothing skipped. Either half missing and the task is discarded.

**The vacuous-task control is the reason this file exists.** A task whose `fail_to_pass` tests
already pass at `base_commit` grades every policy as correct, including one that did nothing at
all. It looks perfect from every direction: the manifest is well-formed, `load_task` accepts it,
STRICT returns PASS, and the corpus quietly contains a task that pays reward for nothing. No
other test in this suite would notice — the verifier is behaving exactly as specified. The only
place to catch it is here, at ingestion, and the catch is one run with no patch.

**What "no patch" has to mean, which is the trap the control caught.** The obvious spelling is
the empty string, and it is wrong: `git apply` refuses an empty diff outright, so STRICT returns
FAIL from `patch-apply` **without running a single test**. Every task then looks live, the
vacuous one included, and the control that was supposed to be the strongest assertion in the
aspect asserts nothing at all. Watched failing exactly that way before `inert_patch` replaced it.
So the no-patch arm applies a real diff that adds one inert file, and this file asserts that the
tests actually ran in it rather than trusting the FAIL.

Two sandboxed reward runs per proof, on synthetic repositories. Offline throughout.
"""

from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

import pytest
from fixtures.repos import BROKEN_ADDER, CALC_FIXED, Fixture, build_task, make_patch

from whetstone.tasks.liveness import Liveness, NotLive, inert_patch, prove_live
from whetstone.verify.verdict import Status

pytestmark = pytest.mark.skipif(
    sys.platform != "darwin",
    reason="liveness runs the reward inside the Seatbelt sandbox, which is macOS-only",
)

#: As in `tests/test_strict.py`: long enough that a slow machine is not misreported, short
#: enough that a hung run does not hold the suite.
_TIMEOUT = 120.0


@pytest.fixture(scope="module")
def honest(tmp_path_factory: pytest.TempPathFactory) -> Fixture:
    """A task that genuinely discriminates: its declared test fails until `add` is fixed."""
    return build_task(tmp_path_factory.mktemp("live-honest"))


@pytest.fixture(scope="module")
def gold(honest: Fixture) -> str:
    """The reference patch — the real fix, generated by git rather than written by hand."""
    return make_patch(honest.origin, {"calc.py": CALC_FIXED})


@pytest.fixture(scope="module")
def proven(honest: Fixture, gold: str, tmp_path_factory: pytest.TempPathFactory) -> Liveness:
    """One proof, paid once and asserted on from several angles."""
    return prove_live(
        honest.task,
        gold,
        sandbox_root=tmp_path_factory.mktemp("live-proof").resolve(),
        timeout=_TIMEOUT,
    )


def test_a_live_task_fails_without_a_patch_and_passes_with_its_own(proven: Liveness) -> None:
    """The whole definition, in the two statuses the ledger will carry."""
    assert proven.without_patch is Status.FAIL
    assert proven.with_patch is Status.PASS


def test_a_live_task_ran_exactly_the_tests_it_declared_and_skipped_none(
    proven: Liveness,
) -> None:
    """PASS is necessary and not sufficient, so both are recorded rather than inferred.

    A skipped test proves nothing about the patch, and an executed set that is not the declared
    set means the task and the run disagree about what was being measured. The ledger states
    both, so a reader is not asked to take PASS as shorthand for them.
    """
    assert proven.executed_matches_declared
    assert proven.skipped == 0


def test_the_no_patch_arm_actually_ran_the_tests(honest: Fixture, proven: Liveness) -> None:
    """The assertion that makes the control mean anything.

    A no-patch arm that FAILs because the diff would not apply is a FAIL that saw no test. It is
    indistinguishable from a real one in the status alone, which is why the count of what ran is
    carried out of the run and asserted here rather than inferred from the FAIL.
    """
    declared = len(honest.task.fail_to_pass) + len(honest.task.pass_to_pass)
    assert proven.executed_without_patch == declared, proven


def test_a_vacuous_task_is_refused(tmp_path: Path) -> None:
    """THE control. A task that passes with no patch must never enter the corpus.

    Its `fail_to_pass` is a test that already passes at `base_commit`, so the task rewards a
    policy that changed nothing. Everything else about it is impeccable — which is precisely why
    the refusal has to happen here and cannot be delegated to the verifier, whose job is to
    report what the tests said and which says PASS entirely correctly.
    """
    vacuous = dataclasses.replace(
        BROKEN_ADDER,
        fail_to_pass=("tests/test_identity.py::test_adding_zero_is_the_identity",),
        pass_to_pass=(),
    )
    fixture = build_task(tmp_path, vacuous, task_id="vacuous")
    patch = make_patch(fixture.origin, {"calc.py": CALC_FIXED})

    with pytest.raises(NotLive) as raised:
        prove_live(
            fixture.task,
            patch,
            sandbox_root=(tmp_path / "sandbox").resolve(),
            timeout=_TIMEOUT,
        )

    message = str(raised.value)
    assert "vacuous" in message, message
    assert "no patch" in message or "without a patch" in message, message


def test_a_task_its_own_reference_patch_cannot_pass_is_refused(tmp_path: Path) -> None:
    """The other half, and the reason the message names which one failed.

    A task whose gold patch does not make it green is not a task — it is an unpassable
    instance that would grade every policy as wrong, and a corpus of those reports a rate of
    zero that says nothing about any model.
    """
    fixture = build_task(tmp_path, task_id="unpassable")
    useless = make_patch(fixture.origin, {"notes.txt": "nothing to see here\n"})

    with pytest.raises(NotLive) as raised:
        prove_live(
            fixture.task,
            useless,
            sandbox_root=(tmp_path / "sandbox").resolve(),
            timeout=_TIMEOUT,
        )

    message = str(raised.value)
    assert "unpassable" in message, message
    assert "reference patch" in message, message


def test_the_no_patch_arm_is_a_diff_that_applies(tmp_path: Path) -> None:
    """The inert patch is a real diff, not an empty string, and it is inert.

    Two properties, and the second is not decoration: the diff has to apply (an empty string
    does not, and a refused diff runs no tests), and it must touch nothing any test could read
    (or the no-patch arm would not be a no-patch arm).
    """
    fixture = build_task(tmp_path)
    patch = inert_patch()
    assert patch.startswith("diff --git "), patch
    assert "new file mode" in patch, patch
    for held in fixture.task.test_blobs:
        assert held not in patch, f"the inert patch names the operator-held {held!r}"
    assert ".py" not in patch, "the inert patch adds a python file, which pytest may collect"
