"""A donor that carries its own lockfile — the one fact that makes source B cheap.

``donor.py`` builds a *history*; this builds the **packaging** that sits under one, because
`whetstone.tasks.environment` refuses a donor it cannot provision from a lock. The two are kept
apart so the mining fixtures do not have to know about uv, and so a test that is about
provisioning does not have to build a history it never mines.

**The lock is generated by real uv, never hand-written.** A hand-authored ``uv.lock`` would be
this suite asserting about its own idea of uv's format — and the format has a revision number in
it. Generating it costs a few milliseconds, is offline, and means the file under test is the one
uv itself would produce.

**The declared requirement is deliberately unbounded.** ``whetstone-fixture-dep`` with no upper
bound is exactly the shape that made ``pallets__flask-5063`` resolve differently by the calendar
(``verify/task.py``'s docstring). The lock is what answers it, and the fixture is built that way
so the capture under test has a real question to answer rather than a pre-pinned one.

Offline throughout: the only place a distribution may come from is the committed index at
``tests/fixtures/pkgindex``, and uv is told so with ``--offline --no-index --find-links``.
"""

from __future__ import annotations

import subprocess
import sys
from collections.abc import Mapping, Sequence
from dataclasses import replace
from pathlib import Path

from fixtures.repos.donor import DONOR_HISTORY, DonorCommit

#: The committed local index — two wheels of one package. See its README for why it exists.
INDEX = Path(__file__).resolve().parent.parent / "pkgindex"

#: The two files a lockfile donor carries, named here because both the capture under test and
#: the fixtures below have to agree on the spelling.
PYPROJECT = "pyproject.toml"
LOCKFILE = "uv.lock"

_PYPROJECT_TEMPLATE = """\
[project]
name = "{name}"
version = "0.0.0"
requires-python = ">={python}"
dependencies = [{dependencies}]

[tool.uv]
package = false
"""


def locked_project_files(
    scratch: Path,
    *,
    name: str = "donor",
    dependencies: Sequence[str] = (),
    index: Path | None = INDEX,
) -> dict[str, str]:
    """``{pyproject.toml: ..., uv.lock: ...}`` for a project pinned by a real ``uv lock``.

    Returned as file *contents* rather than as a directory so a caller can commit them into a
    donor's history at whichever commit it wants them to exist from — which matters, because the
    miner provisions at a candidate's **parent**, so packaging introduced halfway through a
    history would leave the earlier candidates unprovisionable.

    ``requires-python`` is pinned to the running interpreter's own minor version so that
    ``uv sync --python sys.executable`` is satisfiable; a lock that demanded a python this suite
    is not running would fail for a reason that has nothing to do with the capture.
    """
    project = Path(scratch)
    project.mkdir(parents=True, exist_ok=True)
    declared = ", ".join(f'"{requirement}"' for requirement in dependencies)
    (project / PYPROJECT).write_text(
        _PYPROJECT_TEMPLATE.format(
            name=name,
            python=f"{sys.version_info.major}.{sys.version_info.minor}",
            dependencies=declared,
        )
    )

    argv = ["lock", "--project", str(project), "--python", sys.executable, "--offline"]
    if index is not None:
        argv += ["--no-index", "--find-links", str(index)]
    _uv(argv)

    return {
        PYPROJECT: (project / PYPROJECT).read_text(),
        LOCKFILE: (project / LOCKFILE).read_text(),
    }


def locked_history(
    packaging: Mapping[str, str],
    history: Sequence[DonorCommit] = DONOR_HISTORY,
) -> tuple[DonorCommit, ...]:
    """The mining history with `packaging` present from the **seed commit** onward.

    Not appended as a final commit: the miner provisions at each candidate's parent, and a
    ``uv.lock`` that arrives late would make every earlier candidate unprovisionable — which
    would be the fixture, not the miner, deciding what can be mined.
    """
    seed, *rest = history
    return (replace(seed, changes={**seed.changes, **packaging}), *rest)


def _uv(args: list[str]) -> None:
    """uv, with its failure surfaced in full — a half-written lock fails later and opaquely."""
    completed = subprocess.run(["uv", *args], capture_output=True, text=True, check=False)
    if completed.returncode != 0:
        raise RuntimeError(f"uv {' '.join(args)} failed: {completed.stderr.strip()}")


__all__ = ["INDEX", "LOCKFILE", "PYPROJECT", "locked_history", "locked_project_files"]
