"""The control arm: proof that the harness could have reached PASS, taken in the same run.

Without it, **"all three candidates solved zero" and "the harness was broken" are the same
observation.** Both arrive as a column of zeroes; they have opposite meanings and opposite fixes;
and P1's pivot signal — whether to change base, change prompt, or change task family — rests
entirely on telling them apart (`docs/ROADMAP.md:387-389`). A bake-off that cannot distinguish
them publishes a number that means nothing, which is worse than publishing none.

So every candidate's run carries two probes per task, under the **same provisioning** the rollouts
get, using the **same shipped STRICT verifier**:

* `inert_patch()` — a real diff that changes nothing any test can read — must reach **FAIL**. If
  it reaches PASS the task was never red, and every policy graded against it is graded correct.
* the task's own reference patch, **re-derived from the donor**, must reach **PASS**. If it
  cannot, no patch could, and a zero says nothing about any model.

Either half wrong and the run is UNVERIFIED: the records are still findings, but nothing may be
ranked off them. UNVERIFIED never counts as a win, and it must never count as a loss either.

**The pre-flight is the subtle half.** A re-derived reference that touches an operator-held test
path is refused by STRICT before anything runs — correctly, that is the cheat-scope check doing
its job — and the refusal is indistinguishable from "the harness cannot reach PASS". That would
raise a false alarm about the very thing this arm exists to establish. It never fired across the
66 mined manifests and it costs one set comparison, so the reference is checked against
`task.test_blobs` before it is used, and a collision is a **skip with a reason** rather than a
control failure.

**Source A has no donor, and that is not a defect to be worked around quietly.** A SWE-bench
instance is a dataset record: there is no local repository holding the fixing commit, so nothing
can be re-derived from a `provenance.commit` it does not have. Its gold patch is committed instead,
in `tasks/public/pool.json`, and the control arm reads it from there — the fallback the harness
spec declared before any of this ran. Two derivations, one per source, and every record says which
one produced it, because "re-derived from the user's own donor" and "read out of a committed
dataset" are different provenance and a report that blurred them would be claiming the stronger of
the two for both.

**No model, no `mlx`, no network.** The control arm never asks a base for anything — it is about
the harness — so nothing here needs a generator at all. The pools below are fixtures written into
`tmp_path`; the committed 3.2 MB one is never read here.
"""

from __future__ import annotations

import json
import shutil
from collections.abc import Mapping
from pathlib import Path

from fixtures.repos import CALC_FIXED, build_task, make_patch
from fixtures.repos.mined import MINED_CALC_FIXED, MINED_README_AFTER, build_mined_task

from whetstone.bakeoff.control import Control, Origin, harness_status, probe, reference_patch
from whetstone.bakeoff.scoring import Interpreters
from whetstone.tasks.fetch import POOL_SCHEMA
from whetstone.verify.task import load_task
from whetstone.verify.verdict import Status

#: The repository root, for the two committed artefacts the last test reads rather than fabricates.
REPO_ROOT = Path(__file__).resolve().parents[2]

#: Generous enough that a two-commit donor with one module and one pytest file can never reach it,
#: so an UNVERIFIED in this file always means something went wrong rather than something ran slow.
TIMEOUT = 120.0

#: The one eligible source-A instance, spelled as the real corpus spells it. Used as a fixture
#: task's `task_id` because that is the join `whetstone.tasks.public` writes — the manifest's
#: `task_id` *is* the instance id — and a test that invented a different join would pass while the
#: real corpus went on skipping.
INSTANCE = "pallets__flask-4045"


def _pool(path: Path, patches: Mapping[str, str]) -> Path:
    """A source-A pool carrying `patches`, keyed by instance id, and nothing else that matters.

    Written rather than borrowed from `tasks/public/pool.json`: the committed pool is 3.2 MB of
    real dataset and its gold patches only apply to repositories that are cloned from GitHub. The
    shape is what is under test — `read_pool` is the reader, so the fixture has to satisfy it —
    and the patches are generated by git against the fixture's own origin, so a refusal here is
    never a diff that simply failed to apply.
    """
    path.write_text(
        json.dumps(
            {
                "schema": POOL_SCHEMA,
                "instances": [
                    {
                        "instance_id": instance_id,
                        "repo": "pallets/flask",
                        "base_commit": "0" * 40,
                        "environment_setup_commit": "0" * 40,
                        "problem_statement": "add() subtracts.",
                        "patch": patch,
                        # The held tests SWE-bench would apply. Carried because `read_pool`
                        # requires the column, and deliberately never read by the control arm:
                        # the reward's held tests come from the manifest's `test_blobs`.
                        "test_patch": "",
                        "fail_to_pass": ["tests/test_addition.py::test_add_is_addition"],
                        "pass_to_pass": [],
                    }
                    for instance_id, patch in patches.items()
                ],
            }
        ),
        encoding="utf-8",
    )
    return path


def test_the_control_arm_proves_the_harness_can_reach_both_verdicts(tmp_path: Path) -> None:
    """Inert patch FAILs, re-derived reference PASSes: the harness is provably intact.

    This is the assertion that gives an all-zero bake-off its meaning. With it, a column of
    zeroes is a statement about the bases; without it, the same column is consistent with a
    verifier that never applied a patch to the tree it verified — which is a defect this
    repository has already shipped once and closed (`tests/adversarial/test_inert_checkout.py`).
    """
    fixture = build_mined_task(tmp_path / "task")

    result = probe(
        candidate="any-base",
        task=fixture.task,
        sandbox_root=tmp_path / "control",
        timeout=TIMEOUT,
        interpreters=Interpreters(workspace=tmp_path / "envs"),
    )

    assert (result.control, result.without_patch, result.with_reference) == (
        Control.INTACT,
        Status.FAIL,
        Status.PASS,
    ), (
        "WHY THIS IS A FAILURE: the harness could not be shown to discriminate on this task — a "
        "patch that changes nothing must FAIL it and the commit's own fix must PASS it. Until "
        "both are observed in the same run, under the same provisioning, a candidate scoring "
        f"zero is indistinguishable from a harness that grades nothing. Got {result.control!r}, "
        f"without_patch={result.without_patch!r}, with_reference={result.with_reference!r}: "
        f"{result.detail}"
    )


def test_the_reference_patch_is_the_commits_own_fix_without_its_tests(tmp_path: Path) -> None:
    """Re-derived from the donor: every non-test path the commit touched, and no other.

    Asserted separately from the verdict above because "the reference reached PASS" is also what
    a reference containing the *test* file would produce — the restore would simply overwrite it
    — so the PASS alone does not prove the derivation kept the right paths. A reference carrying
    the held test is a reference STRICT refuses as a cheat, and the pre-flight below depends on
    this derivation being the thing that decides.
    """
    fixture = build_mined_task(tmp_path / "task")

    reference = reference_patch(fixture.task)

    assert reference.diff is not None, (
        f"WHY THIS IS A FAILURE: the task names its donor, its commit and its parent, so its own "
        f"fix is re-derivable and the control arm has something to prove PASS with. Refusing to "
        f"derive it turns every task into a skip and leaves the run unproven: {reference.reason}"
    )
    # The lines the diff ADDS, with git's marker stripped. Compared against the fix's own changed
    # line rather than against the whole file, because the unchanged lines around it are context
    # and a diff that carried them as additions would be rewriting the file rather than fixing it.
    added = {line[1:] for line in reference.diff.splitlines() if line.startswith("+")}
    assert MINED_CALC_FIXED.splitlines()[-1] in added, (
        "WHY THIS IS A FAILURE: the re-derived reference does not add the line the commit's fix "
        f"added, so whatever it contains is not that commit's patch:\n{reference.diff}"
    )
    assert "README.md" in reference.diff and MINED_README_AFTER.splitlines()[-1] in added, (
        "WHY THIS IS A FAILURE: the commit also touched a non-`.py` file and the derivation "
        "dropped it. A reference patch that is not the whole commit minus its tests does not "
        f"reproduce the commit, and any verdict it earns is about a patch nobody wrote:\n"
        f"{reference.diff}"
    )
    assert "tests/test_addition.py" not in reference.diff, (
        "WHY THIS IS A FAILURE: the re-derived reference carries the operator-held test file. "
        "STRICT refuses a patch touching a held path before anything runs, so the control arm "
        "would read its own cheat-scope refusal as `the harness cannot reach PASS` — a false "
        f"alarm about the exact thing this arm exists to rule out:\n{reference.diff}"
    )


def test_a_task_that_passes_with_no_patch_breaks_the_control_arm_loudly(tmp_path: Path) -> None:
    """The inert patch reaching PASS is a fact about the task or the checkout, never about a base.

    This is the shape a broken harness wears in public. A task whose declared failing test already
    passes at `base_commit` grades *every* policy as correct — including one that emitted nothing
    — and it looks, from the outside, exactly like a base that solved it. `tests/adversarial/
    test_inert_checkout.py` records that this repository has already shipped one version of this
    defect: a task PASSED with no patch applied, because the tests imported an editable install
    rooted at a different checkout.

    So the response is BROKEN and not a quiet skip, and it takes the whole run's ranking with it.
    """
    fixture = build_mined_task(tmp_path / "task", vacuous=True)

    result = probe(
        candidate="any-base",
        task=fixture.task,
        sandbox_root=tmp_path / "control",
        timeout=TIMEOUT,
        interpreters=Interpreters(workspace=tmp_path / "envs"),
    )

    assert result.control is Control.BROKEN, (
        "WHY THIS IS A FAILURE: a task that passes with a patch changing nothing was accepted as "
        "a sound control. Every candidate would score a win on it, that win would be the "
        f"harness's rather than the base's, and the bake-off would report it as a base's. Got "
        f"{result.control!r} ({result.without_patch!r})"
    )
    assert result.without_patch is Status.PASS
    assert harness_status([result]) is Status.UNVERIFIED, (
        "WHY THIS IS A FAILURE: the run was not marked UNVERIFIED despite a broken control. "
        "UNVERIFIED never counts as a win — and a run whose harness grades nothing must not be "
        f"ranked in either direction. Got {harness_status([result])!r}"
    )
    assert "base_commit" in result.detail or "changes nothing" in result.detail, (
        "WHY THIS IS A FAILURE: the control failed without saying what to go and look at. The "
        "two candidate causes — a task that was never red, and a checkout the patch never "
        f"reached — have entirely different fixes. Got {result.detail!r}"
    )


def test_a_reference_that_touches_a_held_test_is_skipped_with_a_reason(tmp_path: Path) -> None:
    """The pre-flight: a collision is a skip, never a control failure and never a silent use.

    STRICT refuses any patch touching an operator-held path before a single test runs — the
    cheat-scope check doing its job. A control arm that handed such a reference to STRICT would
    read that refusal as "the harness cannot reach PASS" and mark the entire run UNVERIFIED, which
    is a false alarm about the one thing the arm exists to rule out.

    The fixture's commit edits a root `conftest.py` the manifest holds as its cheat-10 floor.
    `is_test_path` correctly calls that file source rather than test code, so it lands in the
    derived path set — which is exactly why the check is against `test_blobs` and not against a
    naming convention.
    """
    fixture = build_mined_task(tmp_path / "task", held_conftest=True)

    reference = reference_patch(fixture.task)
    result = probe(
        candidate="any-base",
        task=fixture.task,
        sandbox_root=tmp_path / "control",
        timeout=TIMEOUT,
        interpreters=Interpreters(workspace=tmp_path / "envs"),
    )

    assert reference.diff is None, (
        "WHY THIS IS A FAILURE: a reference patch touching an operator-held path was handed back "
        "for use. STRICT would refuse it as a cheat before anything ran, and the control arm "
        f"would record the reward working correctly as the harness being broken:\n{reference.diff}"
    )
    assert "conftest.py" in reference.reason, (
        "WHY THIS IS A FAILURE: the skip does not name the path that collided, so nobody can "
        f"tell a held-path collision from a missing donor. Got {reference.reason!r}"
    )
    assert (result.control, result.with_reference) == (Control.SKIPPED, None), (
        "WHY THIS IS A FAILURE: a task the harness could not be checked on was recorded as "
        "something other than a skip. A skip is an ordinary gap the remaining tasks close; a "
        f"BROKEN stops the whole run being ranked. Got {result.control!r}"
    )
    assert harness_status([result]) is Status.UNVERIFIED, (
        "WHY THIS IS A FAILURE: a run in which every probe was skipped established nothing about "
        "the harness, and `nothing went wrong` is not proof that anything went right. It has to "
        f"fall to UNVERIFIED. Got {harness_status([result])!r}"
    )


def test_a_renamed_path_carries_both_of_its_names_into_the_reference(tmp_path: Path) -> None:
    """git reports a rename as ONE record with TWO paths, and both halves are needed.

    Every other name-status record is a status and one path, so a parser consuming a fixed number
    of fields desynchronises the moment a commit contains a rename: it would read the destination
    path as the next record's status letter and mis-parse every remaining file in that commit.
    Silently — the derived patch would simply be missing files, and the control arm would report
    "the harness cannot reach PASS" for a commit whose fix it had itself truncated.

    Both names are kept because a rename is a deletion and a creation: a reference patch carrying
    only one of them does not apply.
    """
    fixture = build_mined_task(tmp_path / "task", renamed=True)

    reference = reference_patch(fixture.task)
    result = probe(
        candidate="any-base",
        task=fixture.task,
        sandbox_root=tmp_path / "control",
        timeout=TIMEOUT,
        interpreters=Interpreters(workspace=tmp_path / "envs"),
    )

    assert reference.diff is not None, (
        f"WHY THIS IS A FAILURE: a commit containing a rename produced no reference patch at "
        f"all: {reference.reason}"
    )
    assert "helper.py" in reference.diff and "helpers.py" in reference.diff, (
        "WHY THIS IS A FAILURE: the reference patch names only one side of the rename, so it "
        "either deletes a file without creating its replacement or creates one without removing "
        f"the original. Neither applies:\n{reference.diff}"
    )
    assert result.control is Control.INTACT, (
        "WHY THIS IS A FAILURE: a commit whose fix included a rename could not be replayed, so "
        "the harness would be reported broken on every such task — and roughly a fifth of real "
        f"red-to-green commits touch more than a single source file. Got {result.control!r}: "
        f"{result.detail}"
    )


def test_a_source_a_instance_takes_its_reference_from_the_committed_pool(tmp_path: Path) -> None:
    """The declared fallback, and the reason the first scored bake-off aborted without it.

    A SWE-bench instance has no donor: `provenance` carries an `instance_id` and no commit, so
    there is nothing to diff parent-to-child and `reference_patch` had nothing to offer. The public
    task's probe was therefore SKIPPED, source A's run reached no INTACT at all, and `rankable`
    refused the whole sweep — correctly, and after a night of generation. The gold patch was
    committed in `tasks/public/pool.json` the entire time.
    """
    fixture = build_task(tmp_path / "task", task_id=INSTANCE)
    pool = _pool(
        tmp_path / "pool.json", {INSTANCE: make_patch(fixture.origin, {"calc.py": CALC_FIXED})}
    )

    reference = reference_patch(fixture.task, pool=pool)
    result = probe(
        candidate="any-base",
        task=fixture.task,
        sandbox_root=tmp_path / "control",
        timeout=TIMEOUT,
        interpreters=Interpreters(workspace=tmp_path / "envs"),
        pool=pool,
    )

    assert reference.diff is not None, (
        f"WHY THIS IS A FAILURE: the instance's gold patch is committed and was not used, so "
        f"source A cannot be controlled for at all — and a source with no INTACT probe takes the "
        f"whole run's ranking with it: {reference.reason}"
    )
    assert (result.control, result.without_patch, result.with_reference) == (
        Control.INTACT,
        Status.FAIL,
        Status.PASS,
    ), (
        f"WHY THIS IS A FAILURE: the harness could not be shown to discriminate on the one "
        f"eligible public instance, so nothing measured on source A is evidence about any base. "
        f"Got {result.control!r}, without_patch={result.without_patch!r}, "
        f"with_reference={result.with_reference!r}: {result.detail}"
    )
    assert harness_status([result]) is Status.PASS, (
        "WHY THIS IS A FAILURE: a run whose only probe was INTACT was still refused, so source A "
        f"could never be ranked however sound its harness. Got {harness_status([result])!r}"
    )


def test_every_reference_says_which_origin_it_came_from(tmp_path: Path) -> None:
    """Two derivations, two provenances, and the record has to name which one it got.

    They are not equally strong. Source B's reference is re-derived from the user's own donor —
    the commit is on the machine and the diff is computed now. Source A's is read out of a
    committed dataset artefact, which nobody in this project re-derived from anything. A report
    that published both as "the task's own reference patch" would claim the first for the second,
    so the distinction is carried on the record rather than reconstructed later from the source.
    """
    mined = build_mined_task(tmp_path / "mined")
    public = build_task(tmp_path / "public", task_id=INSTANCE)
    pool = _pool(
        tmp_path / "pool.json", {INSTANCE: make_patch(public.origin, {"calc.py": CALC_FIXED})}
    )

    from_donor = reference_patch(mined.task, pool=pool)
    from_pool = reference_patch(public.task, pool=pool)

    assert (from_donor.origin, from_pool.origin) == (Origin.DONOR, Origin.POOL), (
        f"WHY THIS IS A FAILURE: the two references are indistinguishable once recorded, so the "
        f"report cannot disclose that source A's control ran against a committed gold patch while "
        f"source B's was re-derived. Got {from_donor.origin!r} and {from_pool.origin!r}"
    )
    assert reference_patch(public.task, pool=None).origin is Origin.NONE, (
        "WHY THIS IS A FAILURE: a reference that does not exist was still labelled with an origin "
        "it could have come from, so a skip reads on the record as a derivation that happened"
    )


def test_an_instance_absent_from_the_pool_is_skipped_and_named(tmp_path: Path) -> None:
    """Missing from the pool is a skip that names the instance — never BROKEN, never silent.

    BROKEN would stop the entire run being ranked, and the cause would be a task the pool does not
    carry: a fact about which dataset artefact was passed on the command line, not about the
    verifier. The instance id is in the message because the operator's fix is to pass the pool that
    has it, and they cannot do that if the skip does not say which one is missing.
    """
    fixture = build_task(tmp_path / "task", task_id=INSTANCE)
    pool = _pool(tmp_path / "pool.json", {"astropy__astropy-12907": "diff --git a/x b/x\n"})

    reference = reference_patch(fixture.task, pool=pool)
    result = probe(
        candidate="any-base",
        task=fixture.task,
        sandbox_root=tmp_path / "control",
        timeout=TIMEOUT,
        interpreters=Interpreters(workspace=tmp_path / "envs"),
        pool=pool,
    )

    assert reference.diff is None, (
        "WHY THIS IS A FAILURE: a reference patch was produced for an instance the pool does not "
        f"carry, so it came from somewhere nobody can name. Got:\n{reference.diff}"
    )
    assert INSTANCE in reference.reason, (
        f"WHY THIS IS A FAILURE: the skip does not name the instance that was missing, so an "
        f"operator holding the wrong pool cannot tell which record to go and find. Got "
        f"{reference.reason!r}"
    )
    assert result.control is Control.SKIPPED, (
        f"WHY THIS IS A FAILURE: a pool that does not carry the instance was reported as a broken "
        f"harness, which stops every candidate being ranked over a missing dataset record. Got "
        f"{result.control!r}: {result.detail}"
    )


def test_a_pool_patch_touching_a_held_test_is_refused_before_it_is_used(tmp_path: Path) -> None:
    """The pre-flight applies to the pool exactly as it applies to the donor. Adversarial.

    SWE-bench splits its records into `patch` and `test_patch` precisely so the gold fix touches no
    test, so this shape is synthesised rather than observed. It is still the one that has to be
    checked: the pool is a 3.2 MB artefact fetched from a dataset, nobody in this project wrote its
    contents, and a `patch` field that reached into `tests/` would be handed straight to STRICT —
    which would refuse it as a cheat before anything ran, and the control arm would record the
    reward's own scope check as "the harness cannot reach PASS" and un-rank the run.
    """
    fixture = build_task(tmp_path / "task", task_id=INSTANCE)
    cheating = make_patch(
        fixture.origin,
        {"tests/test_addition.py": "def test_add_is_addition():\n    assert True\n"},
    )
    pool = _pool(tmp_path / "pool.json", {INSTANCE: cheating})

    reference = reference_patch(fixture.task, pool=pool)
    result = probe(
        candidate="any-base",
        task=fixture.task,
        sandbox_root=tmp_path / "control",
        timeout=TIMEOUT,
        interpreters=Interpreters(workspace=tmp_path / "envs"),
        pool=pool,
    )

    assert reference.diff is None, (
        "WHY THIS IS A FAILURE: a pool patch that edits an operator-held test was handed back for "
        "use. STRICT refuses it as a cheat before a test runs, and the control arm would read the "
        f"reward working correctly as the harness being broken:\n{reference.diff}"
    )
    assert "tests/test_addition.py" in reference.reason, (
        f"WHY THIS IS A FAILURE: the refusal does not name the held path the pool patch reached "
        f"for, so nobody can tell it from an instance the pool never carried. Got "
        f"{reference.reason!r}"
    )
    assert (result.control, result.with_reference) == (Control.SKIPPED, None), (
        f"WHY THIS IS A FAILURE: the collision was recorded as something other than a skip. A "
        f"BROKEN here would blame the verifier for catching exactly what it exists to catch. Got "
        f"{result.control!r}"
    )


def test_source_b_never_falls_back_to_the_pool(tmp_path: Path) -> None:
    """A private task whose donor is gone is a skip about the donor, not a lookup in a dataset.

    The two derivations stay distinct on purpose. A source-B task that quietly took its reference
    from a public dataset would be controlled against a patch for a *different repository* that
    happened to share an id, and the probe's INTACT would be about neither. So the donor route
    fails as the donor route: `origin` stays NONE and the reason names the checkout.
    """
    fixture = build_mined_task(tmp_path / "task", task_id=INSTANCE)
    shutil.rmtree(fixture.donor)
    pool = _pool(tmp_path / "pool.json", {INSTANCE: "diff --git a/calc.py b/calc.py\n"})

    reference = reference_patch(fixture.task, pool=pool)

    assert reference.diff is None, (
        "WHY THIS IS A FAILURE: a private task took its reference from the public pool. The patch "
        "it would be controlled against was written for another repository entirely, and an "
        f"INTACT earned that way is evidence about nothing:\n{reference.diff}"
    )
    assert reference.origin is Origin.NONE, (
        f"WHY THIS IS A FAILURE: the record claims an origin for a reference that was never "
        f"obtained. Got {reference.origin!r}"
    )
    assert "donor" in reference.reason, (
        f"WHY THIS IS A FAILURE: the skip does not say the donor could not be read, so a missing "
        f"checkout looks like a missing dataset record. Got {reference.reason!r}"
    )


def test_the_one_eligible_instance_resolves_against_the_committed_pool() -> None:
    """The real artefacts, not a fixture: `pallets__flask-4045` against `tasks/public/pool.json`.

    Everything above proves the mechanism on synthetic records. This proves the mechanism reaches
    the instance the bake-off actually runs — the join between a manifest's `task_id` and a pool
    record's `instance_id` is a convention two modules share, and a fixture that invented its own
    would pass while the real public probe went on skipping. Which is exactly what happened: the
    aborted run's public task was SKIPPED, and every test in this file was green at the time.

    The disjointness is asserted here rather than assumed. SWE-bench splits `patch` from
    `test_patch` so the gold fix touches no test, and this instance's does touch only
    `src/flask/blueprints.py` — but "the dataset promises it" is not a check, and the consequence
    of being wrong is STRICT refusing the reference at `patch-scope` and the run losing its
    ranking.

    Reads two committed files and nothing else: no network, no clone, no model. `git apply
    --numstat` parses the diff without applying it anywhere.
    """
    manifest = REPO_ROOT / "tasks" / "public" / "instances" / f"{INSTANCE}.json"
    pool = REPO_ROOT / "tasks" / "public" / "pool.json"
    task = load_task(manifest)

    reference = reference_patch(task, pool=pool)

    assert reference.origin is Origin.POOL, (
        f"WHY THIS IS A FAILURE: the one eligible public instance did not take its reference from "
        f"the committed pool, so source A cannot prove the harness grades anything and no run "
        f"carrying it can be ranked. Got {reference.origin!r}: {reference.reason}"
    )
    assert reference.diff is not None and "src/flask/blueprints.py" in reference.diff, (
        f"WHY THIS IS A FAILURE: the resolved reference is not this instance's gold fix, so "
        f"whatever the control arm would run is a patch for something else:\n{reference.diff}"
    )
    assert set(task.test_blobs) == {
        "tests/conftest.py",
        "tests/test_basic.py",
        "tests/test_blueprints.py",
    }, (
        f"WHY THIS IS A FAILURE: the held set moved, so the disjointness this test checks is no "
        f"longer the disjointness that matters. Got {sorted(task.test_blobs)}"
    )
