"""Nothing enters the corpus unproven: two runs of the shipped reward, per minted task.

A task is **live** when it discriminates. With no patch it must **FAIL**; with its own reference
patch it must **PASS**, having run exactly the node ids it declared and skipped none of them.
Either half missing and the task is discarded with the missing half named (PRD M8, G1).

**The vacuous task is what this exists to refuse.** A task whose `fail_to_pass` tests already
pass at `base_commit` grades every policy as correct — including one that emitted nothing. It is
invisible from every other angle: the manifest is well-formed, `load_task` accepts it, and STRICT
answers PASS entirely correctly, because the tests really did pass. The verifier cannot catch
this and should not try; a reward that second-guessed its own tests would be a judge. The only
place to catch it is ingestion, and the catch is one run with no patch.

**What "no patch" has to mean, and it is not the empty string.** `git apply` refuses an empty
diff, so `verify_strict(task, "")` returns FAIL from `patch-apply` **before a single test runs**.
Every task then looks live — the vacuous one included — and the strongest control in the aspect
silently asserts nothing. Measured, not anticipated: the vacuous-task test was watched passing
liveness under exactly that implementation. So the no-patch arm applies `inert_patch()`, a real
diff that adds one inert non-python file, and the proof additionally requires that **tests
actually ran** in that arm. A FAIL nobody ran a test for is not evidence about a task.

The reward is the shipped `verify_strict`, unchanged and unaided: a liveness proof produced by a
private, more forgiving verifier would prove something about that verifier instead.

No model, no network. Two sandboxed pytest runs per task.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from whetstone.verify.strict import StrictResult, verify_strict
from whetstone.verify.task import Task
from whetstone.verify.verdict import Status, Verdict

#: The path the inert patch creates. Dot-prefixed, no `.py` suffix, and named after what it is,
#: so that a reader who finds one in a checkout knows immediately which run left it there. It
#: must not be a python file: pytest is invoked on the declared node ids, but a stray module in
#: the rootdir is one import hook away from mattering, and the no-patch arm has to be inert.
NO_PATCH_PATH = ".whetstone-no-patch"

#: The verdict kinds that mean the run never reached the tests. A no-patch arm that FAILs for one
#: of these has proved nothing about the task, so it is refused rather than counted.
_BEFORE_ANY_TEST = frozenset({"patch-apply", "checkout", "task-blobs"})


class NotLive(ValueError):
    """This task does not discriminate. Discarded, with the half that failed named.

    Raised rather than returned, because a caller that forgot to check a boolean would mint the
    task anyway — and the whole point is that nothing unproven reaches the corpus.
    """


@dataclass(frozen=True)
class Liveness:
    """The evidence that one task discriminates, in the shape the ledger commits.

    `executed_matches_declared` and `skipped` are recomputed here rather than read off the PASS.
    A PASS already implies both, so this is deliberate redundancy: the ledger is what a reader
    with none of the data has, and "PASS, therefore the executed set matched" asks them to know
    the verifier's internals. It states them instead.

    `executed_without_patch` is the count of node ids the no-patch arm actually ran. It is the
    field that makes the FAIL in `without_patch` mean something.
    """

    task_id: str
    without_patch: Status
    with_patch: Status
    executed_without_patch: int
    executed_matches_declared: bool
    skipped: int


def inert_patch(path: str = NO_PATCH_PATH) -> str:
    """A diff that applies cleanly and changes nothing any test can read.

    Hand-built rather than generated by git, and this is the one place in the project where that
    is right: generating it would need a checkout of the task's own repository, which is the very
    thing the reward run is about to make. The diff is a single new file with no context lines —
    the one patch shape that cannot fail to apply for a reason that has nothing to do with the
    task, unless the path already exists, which `prove_live` detects and reports.
    """
    return (
        f"diff --git a/{path} b/{path}\n"
        "new file mode 100644\n"
        "--- /dev/null\n"
        f"+++ b/{path}\n"
        "@@ -0,0 +1 @@\n"
        "+this task was verified with no patch applied\n"
    )


def prove_live(
    task: Task,
    reference: str,
    *,
    sandbox_root: Path | str,
    timeout: float,
    interpreter: Path | str | None = None,
) -> Liveness:
    """Prove `task` discriminates, or raise `NotLive` naming the half that failed.

    `timeout` and `interpreter` have no defaults for the same reason `verify_strict` gives them
    none: a limit or an interpreter inherited from somewhere else turns a task's discard into
    something nobody can explain.

    The no-patch arm runs first. It is the cheaper refusal and it is the one that catches the
    vacuous task, so a corpus being minted against a mistaken `fail_to_pass` fails fast rather
    than after a reference run per candidate.
    """
    without = verify_strict(
        task,
        inert_patch(),
        sandbox_root=sandbox_root,
        timeout=timeout,
        run_id=f"{task.task_id}-without-patch",
        interpreter=interpreter,
    )
    _require_the_tests_ran(task, without)
    if without.status is not Status.FAIL:
        raise NotLive(
            f"task {task.task_id!r} did not fail without a patch — it reduced to "
            f"{without.status.value} with nothing applied. Its declared fail_to_pass tests "
            f"already pass at base_commit, so the task rewards a policy that changed nothing, "
            f"and every policy graded against it would be graded correct. The task is vacuous "
            f"and is discarded rather than minted"
        )

    with_patch = verify_strict(
        task,
        reference,
        sandbox_root=sandbox_root,
        timeout=timeout,
        run_id=f"{task.task_id}-with-patch",
        interpreter=interpreter,
    )
    if with_patch.status is not Status.PASS:
        raise NotLive(
            f"task {task.task_id!r} did not pass under its own reference patch — it reduced to "
            f"{with_patch.status.value}: "
            f"{_why(with_patch.verdicts)}. A task its own gold patch cannot pass grades every "
            f"policy as wrong, and a corpus of those reports a rate of zero that says nothing "
            f"about any model. The task is discarded rather than minted"
        )

    declared = (*task.fail_to_pass, *task.pass_to_pass)
    executed = with_patch.executed or ()
    return Liveness(
        task_id=task.task_id,
        without_patch=without.status,
        with_patch=with_patch.status,
        executed_without_patch=len(without.executed or ()),
        executed_matches_declared=(
            set(executed) == set(declared) and len(executed) == len(declared)
        ),
        skipped=_skipped(with_patch.verdicts),
    )


def _require_the_tests_ran(task: Task, result: StrictResult) -> None:
    """Refuse a no-patch arm that never reached pytest.

    The failure this closes is the whole reason `inert_patch` is not the empty string: a FAIL
    from `patch-apply` looks identical to a FAIL from the declared tests in the status alone, and
    a task "proved live" by a diff that never applied has been proved nothing.
    """
    reached = {verdict.kind for verdict in result.verdicts} & _BEFORE_ANY_TEST
    if reached or result.executed is None:
        raise NotLive(
            f"the no-patch run of task {task.task_id!r} never reached the declared tests "
            f"({_why(result.verdicts)}), so its verdict is not evidence about the task. The "
            f"probe patch must apply — check whether {NO_PATCH_PATH!r} already exists at "
            f"base_commit"
        )
    if not result.executed:
        raise NotLive(
            f"the no-patch run of task {task.task_id!r} executed no tests at all, so there is "
            f"nothing its verdict could be about"
        )


def _skipped(verdicts: Sequence[Verdict]) -> int:
    """How many declared tests were skipped, read from the reward's own sub-check.

    `strict._skipped_verdict` reports `0` when none were and the list of node ids when some
    were; both shapes are handled here rather than assumed, because the ledger records a count
    and a `TypeError` at mint time would be a discard with the wrong reason on it.
    """
    for verdict in verdicts:
        if verdict.kind == "skipped":
            observed = verdict.observed
            return len(observed) if isinstance(observed, list) else int(observed or 0)
    return 0


def _why(verdicts: Sequence[Verdict]) -> str:
    """The sub-checks that did not pass, so a discard names its own reason.

    Only the non-passing ones: a discard that listed its passing checks would read like a
    partial success, which is the same honesty rule the CLI applies to its own output.
    """
    failing = [
        f"{verdict.kind}: {verdict.message}"
        for verdict in verdicts
        if verdict.status is not Status.PASS
    ]
    return "; ".join(failing) or "no sub-check reported a failure"


__all__ = ["NO_PATCH_PATH", "Liveness", "NotLive", "inert_patch", "prove_live"]
