"""A source-A pool with the committed artefact's shape and none of its 3.2 MB.

Two things now read the pool — the control arm takes source A's reference patch from it
(``bakeoff.control._from_pool``) and the oracle derivation takes source A's *file set* from the
same patch (``bakeoff.sources``) — so two test modules need to build one. They build it here
rather than each writing its own literal, for the reason the code under test gives for reading it
in one place: a second spelling of the schema would drift, and the copy that drifted would be the
one whose module went on passing against a pool the real reader rejects.

**Written, never borrowed from ``tasks/public/pool.json``.** The committed pool is real dataset:
3.2 MB, and its one gold patch applies only to a checkout of flask cloned from GitHub. A test
that used it would either need the network or would assert against a diff that simply failed to
apply, which is indistinguishable from the refusals these modules are about. What *is* under test
is the shape, so the fixture has to satisfy ``whetstone.tasks.fetch.read_pool`` itself — hence
``POOL_SCHEMA`` imported rather than spelled — and the patches are generated by git against the
fixture repository they act on.

The one test that reads the real committed pool is
``tests/bakeoff/test_oracle_sources.py::test_the_one_eligible_public_instance_derives_one_path``,
which asserts about that artefact specifically and touches no network to do it.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path

from whetstone.tasks.fetch import POOL_SCHEMA


def write_pool(path: Path, patches: Mapping[str, str], *, repo: str = "pallets/flask") -> Path:
    """Write a pool at ``path`` carrying ``patches``, keyed by instance id, and return it.

    Every other column is present because ``read_pool`` requires it and is deliberately
    uninteresting: the two consumers read ``instance_id`` and ``patch`` and nothing else. In
    particular ``test_patch`` — the held tests SWE-bench would apply — is carried and never read,
    because the reward's held tests come from the manifest's ``test_blobs`` rather than from a
    dataset column nobody in this project re-derived.
    """
    path.write_text(
        json.dumps(
            {
                "schema": POOL_SCHEMA,
                "instances": [
                    {
                        "instance_id": instance_id,
                        "repo": repo,
                        "base_commit": "0" * 40,
                        "environment_setup_commit": "0" * 40,
                        "problem_statement": "add() subtracts.",
                        "patch": patch,
                        "test_patch": "",
                        "fail_to_pass": ["tests/test_addition.py::test_add_is_addition"],
                        "pass_to_pass": [],
                    }
                    for instance_id, patch in patches.items()
                ],
            }
        ),
        encoding="utf-8",
    )
    return path


__all__ = ["write_pool"]
